name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    name: Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run tfsec (Terraform Security)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .

      - name: Run Trivy (Docker Image Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'c:\Users\HP\Downloads\devon-beard-2FL8rHzKht8-unsplash.jpg'  # image

  deploy:
    name: Deploy Sealed Secrets
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.29.0'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config

      - name: Apply Sealed Secrets
        run: |
          kubectl apply -f k8s/sealed-secret.yaml
